#!/bin/bash
#Script to set the active class in the navigation bar to the correct page
#By Benjamin Piggott, 2018

#Extract title of html document to determine file name and then forced to lowercase
title=$(grep -Po '(?<=(<title>)).*(?=</title>)' ../html/$1)

#Ensure no item is set to active in the document
sed -e 's/class="active" //g' -i ../html/$1

#Ensure no sub item is also set to active in the document
sed -e 's/class="active-sub" //g' -i ../html/$1


#Checking if document is in a submenu
if grep -e "`echo $title | tr '[:upper:]' '[:lower:]'`" submenu; then
  #If the title is in the submenu file then it is a submenu
  #Getting the correct top level menu name from the submenu file
  menu=$(grep -e "`echo $title | tr '[:upper:]' '[:lower:]'`" submenu |  sed 's/.*://' | tr '[:lower:]' '[:upper:]')

  #Setting top level menu item to active
  sed -i "s|<a href=.*>$menu</a>|<a class=\"active-navbar\" href=\"\">$menu</a>|g" ../html/$1

  #Setting submenu item to active
  sed -i "s|<a href=.*>`echo $title | tr '[:lower:]' '[:upper:]'`</a>|<a class=\"active-sub-navbar\" href=\"$title.html\">`echo $title | tr '[:lower:]' '[:upper:]'`</a>|g" ../html/$1
else
  #If the title is not in the submenu file then it is a top level menu item
  #Setting the top level item to active
  sed -i "s|<a href=.*>`echo $title | tr '[:lower:]' '[:upper:]'`</a>|<a class=\"active-navbar\" href=\"$title.html\">`echo $title | tr '[:lower:]' '[:upper:]'`</a>|g" ../html/$1
fi
