#!/bin/bash
#Script to insert a header and a footer into a html document from a template

#Extracting header and footer from template document
head=$(sed '\,/head,q' ../html/template.html)
foot=$(sed -n '/footer/,$p' ../html/template.html)

#Debugging
echo $head
echo $foot

#Generating a temporary file
temp=$(mktemp)

#Inserting header and footer into the desired document using the temporary file
echo $head >> $temp
cat ../html/$1 >> $temp
echo $foot >> $temp
mv $temp ../html/$1
