#!/bin/bash
#Script to insert a header and a footer into a html document from a template

#Sanitising the input document to ensure only the body section remains in the
#event the document also contains a header and a footer
doc=$(sed -n '/<body>/,/<\/body>/p' ../html/$1)

#Extracting header and footer from template document
head=$(sed '\,/head,q' ../html/template.html)
foot=$(sed -n '/footer/,$p' ../html/template.html)

#Generating a temporary file
temp=$(mktemp)

#Inserting header and footer from the template and the body from the document
#into the temporary file
echo "$head" >> $temp
echo "$doc" >> $temp
echo "$foot" >> $temp

#Replacing the orginal document with the temporary file
mv $temp ../html/$1

#Updating last edit timestamp in the footer of the document
timestamp ../html/$1
