#!/bin/bash
#Script to setup a new html document
#By Benjamin Piggott, 2018

#Insert the header and footer from the standard template
insert ../html/$1

#Update the title of the document to that of the filename
title ../html/$1

#Set the correct navigation bar item to active
active ../html/$1

#Updating last edit timestamp in the footer of the document
timestamp ../html/$1
