#!/bin/bash
#Script to insert a timestamp into the footer of a html document
#By Benjamin Piggott, 2018

#Variable to store current date
today=$(date +%Y-%m-%d)

#Updating timestamp
sed -r -i "s|[0-9]{4}-[0-9]{2}-[0-9]{2}|$today|g" ../html/$1
